### ISSUE TITLE
AttributeError: num_lidar_points_in_box

### ISSUE THREAD

**Issue by xjjs** [caizhongang/waymo_to_kitti_converter#1]
Hi,

there is a line in conver.py:   if filter_empty_3dbox and obj.num_lidar_points_in_box < 1
And the error is as follows:
  File "converter.py", line 360, in save_label
    if filter_empty_3dbox and obj.num_lidar_points_in_box < 1:
AttributeError: num_lidar_points_in_box

The attribute "num_lidar_points_in_box" is not given in https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto

**Comment by caizhongang** [comment]
Thank you for your feedback. This project is still in development and it will get better.

However, the converter runs fine on my side.

**num_lidar_points_in_box** can be found at
https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L83

Can you try the following script?
```python3
import tensorflow as tf
from waymo_open_dataset import dataset_pb2 as open_dataset

tfrecord_file_name = ''  # give one tfrecord here

def read_tfrecord():
    dataset = tf.data.TFRecordDataset(tfrecord_file_name, compression_type='')
    for data in dataset:
        frame = open_dataset.Frame()
        frame.ParseFromString(bytearray(data.numpy()))
        for obj in frame.laser_labels:
             print(obj.num_lidar_points_in_box)

if __name__ == '__main__':
    read_tfrecord()
```

**Comment by xjjs** [comment]
> Thank you for your feedback. This project is still in development and it will get better.
> 
> However, the converter runs fine on my side.
> 
> **num_lidar_points_in_box** can be found at
> https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L83
> 
> Can you try the following script?
> 
> ```python
> import tensorflow as tf
> from waymo_open_dataset import dataset_pb2 as open_dataset
> 
> tfrecord_file_name = ''  # give one tfrecord here
> 
> def read_tfrecord():
>     dataset = tf.data.TFRecordDataset(tfrecord_file_name, compression_type='')
>     for data in dataset:
>         frame = open_dataset.Frame()
>         frame.ParseFromString(bytearray(data.numpy()))
>         for obj in frame.laser_labels:
>              print(obj.num_lidar_points_in_box)
> 
> if __name__ == '__main__':
>     read_tfrecord()
> ```

Thanks for your prompt reply, and I didn't notice the num_lidar_points_in_box before in label.proto.

The above script cannot run successfully in my project:
1.AttributeError: 'Tensor' object has no attribute 'numpy', 
and this can be solved by adding "    tf.enable_eager_execution()"
2.again I meet the attributeError:
2020-05-12 14:17:53.686784: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-12 14:17:53.701024: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2807945000 Hz
2020-05-12 14:17:53.701558: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56489017ac50 executing computations on platform Host. Devices:
2020-05-12 14:17:53.701590: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "temp.py", line 17, in <module>
    read_tfrecord()
  File "temp.py", line 13, in read_tfrecord
    print(obj.num_lidar_points_in_box)
AttributeError: num_lidar_points_in_box

**Comment by xjjs** [comment]
> Thank you for your feedback. This project is still in development and it will get better.
> 
> However, the converter runs fine on my side.
> 
> **num_lidar_points_in_box** can be found at
> https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto#L83
> 
> Can you try the following script?
> 
> ```python
> import tensorflow as tf
> from waymo_open_dataset import dataset_pb2 as open_dataset
> 
> tfrecord_file_name = ''  # give one tfrecord here
> 
> def read_tfrecord():
>     dataset = tf.data.TFRecordDataset(tfrecord_file_name, compression_type='')
>     for data in dataset:
>         frame = open_dataset.Frame()
>         frame.ParseFromString(bytearray(data.numpy()))
>         for obj in frame.laser_labels:
>              print(obj.num_lidar_points_in_box)
> 
> if __name__ == '__main__':
>     read_tfrecord()
> ```

Thanks for your prompt reply. May I know you how to configure the "waymo-open-dataset"? I check the "label.proto" file in my folder, and the line "  optional int32 num_lidar_points_in_box = 7;" is missed. I think we have different version of "waymo-open-dataset". Did you adopt the tensorflow 1.14 or > 2.0?

**Comment by caizhongang** [comment]
> 1.AttributeError: 'Tensor' object has no attribute 'numpy',
and this can be solved by adding " tf.enable_eager_execution()"

Yes, the script is for TensorFlow version >= 2. 

> May I know you how to configure the "waymo-open-dataset"? I check the "label.proto" file in my folder, and the line " optional int32 num_lidar_points_in_box = 7;" is missed. I think we have different version of "waymo-open-dataset". Did you adopt the tensorflow 1.14 or > 2.0?

My TensorFlow version is 2.1.0. I guess that is the problem. You may want to upgrade to TensorFlow 1.15.0, 2.0.0, 2.1.0 and install the precompiled packages accordingly:
```bash
pip3 install waymo-open-dataset-tf-<your-tf-version>==1.2.0 --user
``` 
See details on the official page: https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md
I am not sure if they support other TensorFlow versions but I'd prefer following their system requirement list.

**Comment by caizhongang** [comment]
May I know your tensorflow version?

Also, can you try:
```python3
print(obj)
```
At the error line, just to see what's inside the obj.

Besides, I'd like to confirm that you have installed the correct pre-compiled pip/pip3 packages:
```bash
pip3 install waymo-open-dataset-tf-<your_tf_version>==1.2.0 --user
```
Reference: https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md

**Comment by xjjs** [comment]
> > 1.AttributeError: 'Tensor' object has no attribute 'numpy',
> > and this can be solved by adding " tf.enable_eager_execution()"
> 
> Yes, the script is for TensorFlow version >= 2.
> 
> > May I know you how to configure the "waymo-open-dataset"? I check the "label.proto" file in my folder, and the line " optional int32 num_lidar_points_in_box = 7;" is missed. I think we have different version of "waymo-open-dataset". Did you adopt the tensorflow 1.14 or > 2.0?
> 
> My TensorFlow version is 2.1.0. I guess that is the problem. You may want to upgrade to TensorFlow 1.15.0, 2.0.0, 2.1.0 and install the precompiled packages accordingly:
> 
> ```shell
> pip3 install waymo-open-dataset-tf-<your-tf-version>==1.2.0 --user
> ```
> 
> See details on the official page: https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md
> I am not sure if they support other TensorFlow versions but I'd prefer follow their system requirement list.

thanks for your reply, the branch "r1.0" didn't not include the  line " optional int32 num_lidar_points_in_box = 7;" https://github.com/waymo-research/waymo-open-dataset/blob/r1.0/waymo_open_dataset/label.proto, And I need update my tensorflow and waymo-open-dataset, thanks

**Comment by caizhongang** [comment]
Thank you for your feedback. I will add precautions in the README as soon as I have time.

**Comment by caizhongang** [comment]
Follow-ups, see https://github.com/caizhongang/waymo_to_kitti_converter/issues/2.
