### ISSUE TITLE
About small_gt_generator.py

### ISSUE THREAD

**Issue by mrsempress** [caizhongang/waymo_to_kitti_converter#11]
First of all thanks for the great tool. But I got an error while using small_gt_generator.py.
```
File "tools/small_gt_generator.py", line 47, in main
   frame = file_data['frame_idx']
TypeError: 'TFRecordDatasetV2' object is not subscriptable
```
The parameters I set are as follows:
```
tfrecords_load_dir = '/home/data/waymo/validation'
val_list_load_pathname = '/home/data/waymo/val.txt'
gt_load_pathname = 'gt.bin' # which is produced by gt_generator.py

gt_small_save_pathname = 'small_gt.bin'
```

Am I misunderstanding something?

**Comment by caizhongang** [comment]
Hi @mrsempress , this repo is no longer actively maintained. My best guess is that TensorFlow has changed the way `TFRecordDataset` behaves (as you can see the `V2` in the name). I would suggest directly looking into TF's [documentation](https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset#snapshot) to see if there are suitable methods to get a slice of the data.
