### ISSUE TITLE
AttributeError: num_lidar_points_in_box

### ISSUE THREAD

**Issue by xjjs** [caizhongang/waymo_to_kitti_converter#2]
Hi, 
After I installed the tensorflow=2.1.0 and waymo-open-dataset-tf-2-1-0==1.2.0, I still get the attribute error:

    print(obj.num_lidar_points_in_box)
AttributeError: num_lidar_points_in_box

and I haven't build the "Metrics Computation" and "Python Utilities" successfully,  will it affect?

**Comment by caizhongang** [comment]
Hi,

> and I haven't build the "Metrics Computation" and "Python Utilities" successfully, will it affect?

No, it should not affect.

Can you try:
```python3
print(obj)
````
Just curious to see what's inside.
(This is the follow-up issue on https://github.com/caizhongang/waymo_to_kitti_converter/issues/1)

By the way, when did you download the data? I downloaded the data in early April.

**Comment by xjjs** [comment]
> Hi,
> 
> > and I haven't build the "Metrics Computation" and "Python Utilities" successfully, will it affect?
> 
> No, it should not affect.
> 
> Can you try:
> 
> ```python
> print(obj)
> ```
> 
> Just curious to see what's inside.
> (This is the follow-up issue on #1)
> 
> By the way, when did you download the data? I downloaded the data in early April.

For the data, I only download a few segments in early May. And the result of "print(obj)" is as follows:

box {
  center_x: -20.020040598094056
  center_y: 7.255771617461505
  center_z: 0.5024888653456401
  width: 1.9828961125840503
  length: 4.760235235989989
  height: 1.6800000000000068
  heading: -0.009081201874720168
}
metadata {
  speed_x: 20.330629091724095
  speed_y: 0.2304147476950128
  accel_x: 0.22777614739139299
  accel_y: 0.03386023019193613
}
type: TYPE_VEHICLE
id: "8EFRSwEXBf9P-SzIDRzx0A"

box {
  center_x: 50.41102899917314
  center_y: 3.7574178158320137
  center_z: 0.9634878537108307
  width: 2.0181655979297246
  length: 4.513134775681905
  height: 1.7700000000000102
  heading: -0.005225447353401691
}
metadata {
  speed_x: 17.879238051739502
  speed_y: 0.2714639645808662
  accel_x: -0.11760476277109007
  accel_y: 0.009923281494627609
}
type: TYPE_VEHICLE
id: "VJ3F-NiHmRQh0umylCVJmA"

**Comment by xjjs** [comment]
> Hi,
> 
> > and I haven't build the "Metrics Computation" and "Python Utilities" successfully, will it affect?
> 
> No, it should not affect.
> 
> Can you try:
> 
> ```python
> print(obj)
> ```
> 
> Just curious to see what's inside.
> (This is the follow-up issue on #1)
> 
> By the way, when did you download the data? I downloaded the data in early April.

I have found the problem:
I have followed the instruction on https://github.com/Yao-Shao/Waymo_Kitti_Adapter to copy the pd2 files to waymo_open_dataset, which has conflicts with the waymo-open-dataset-tf-2-1-0==1.2.0, so I just delete the waymo_open_dataset file.

**Comment by caizhongang** [comment]
It seems your tfrecord does not contain **num_lidar_points_in_box**.

> For the data, I only download a few segments in early May

This is strange, I know earlier data releases did not have this attribute (see https://github.com/waymo-research/waymo-open-dataset/issues/117), but if you downloaded it in May, it should be fine.

Did you download the data from the official source at https://waymo.com/open/download/ ?

Also, can you confirm that your python is importing the correct waymo-open-dataset version? It may be better to uninstall the current package and install again.

In addition, can you please give me the filename of the tfrecord you use? I will check on my machine.

**Comment by caizhongang** [comment]
> I have found the problem:
I have followed the instruction on https://github.com/Yao-Shao/Waymo_Kitti_Adapter to copy the pd2 files to waymo_open_dataset, which has conflicts with the waymo-open-dataset-tf-2-1-0==1.2.0, so I just delete the waymo_open_dataset file.

Cool. Let me know if there are any other problems.

I should really start writing the README by the way.

**Comment by xjjs** [comment]
> > I have found the problem:
> > I have followed the instruction on https://github.com/Yao-Shao/Waymo_Kitti_Adapter to copy the pd2 files to waymo_open_dataset, which has conflicts with the waymo-open-dataset-tf-2-1-0==1.2.0, so I just delete the waymo_open_dataset file.
> 
> Cool. Let me know if there are any other problems.
> 
> I should really start writing the README by the way.

It runs successfully without any problem, thanks!
