### ISSUE TITLE
Any tools to convert coordinate reference frames between waymo and kitti?

### ISSUE THREAD

**Issue by alawliat** [caizhongang/waymo_to_kitti_converter#7]
Hi,

First of all, thank you very much for making this tool, it has saved me a significant amount of time.
However, I just wanted to inquire, I have some LiDAR detectors that are trained on the KITTI dataset,
but to evaluate an idea, I must use them on Waymo dataset.

since the coordinate frames are different, the bounding boxes are not around the correct objects. Any ideas how I may be able to convert the Waymo reference frame to kitti?

More specifically, I am referring to step 3 here. 

https://github.com/open-mmlab/OpenPCDet/blob/master/docs/DEMO.md

I am under the impressions that I must first load the bin files into a np array and then apply some transformation but I am really unsure. I would greatly appreciate any help. 

Thank you.

**Comment by caizhongang** [comment]
Hi, the tool is able to convert the waymo data to kitti format with considerations taken for the differences in the ego coordinate systems. You can use the converter.py to convert data to kitti format, inference using your model, and use the prediction_kitti_to_waymo.py to convert the results to waymo format for evaluation. The details can be found in the README
