### ISSUE TITLE
This conversion has lots of issues?

### ISSUE THREAD

**Issue by mariya12290** [caizhongang/waymo_to_kitti_converter#8]
Hey all and @caizhongang 

I checked the conversion data and worked on it for nearly one month. I found that data conversion is not so good for object detection. Here you can see error in the data conversion [this](https://github.com/waymo-research/waymo-open-dataset/issues/326#issue-912723843)

Before using this conversion tool, one has to remove the frames where ground truths are there even objects are invisible. 

Since waymo dataset was designed for lots of purpose. we need to be careful while using waymo dataset

**Comment by DuZzzs** [comment]
@mariya12290 Hi, do you know how to delete invisible object in label txt files after converted? Thank you.

**Comment by mariya12290** [comment]
@DuZzzs  Currently I have no idea. It is very tedious work.  So I left it as it is. If someone has a good way to remove them, please share them with us.
