### ISSUE TITLE
Projected 2D bboxes problems

### ISSUE THREAD

**Issue by ZCMax** [caizhongang/waymo_to_kitti_converter#9]
Hi! Using the converted camera intrinsic and 3D object detection, I calculated the projected 2D bboxes. However, it seems they are often larger than the real object, and it seems there's a distortion problem while visualization. Do you have any suggestions to handle these problems?

**Comment by caizhongang** [comment]
Hi @ZCMax, it is observed that Waymo's annotation is often slightly larger than the actual object. The converter does not perform any additional scaling but faithfully retain the original size.
